model:
  category: anthropic

  anthropic:
    model_name: claude-3-haiku-20240307
    max_tokens: 4096
    temperature: 0.2
    max_retries: 2
    timeout:

indexing:
  activate: true
  type: multimodal   # "multimodal" or "text"
  text:
    collection_name: text_doc
  multimodal:
    collection_name: multimodal_doc

retrieval:
  vectorstore:
    collection_name: multimodal_doc # quiz_me_multi_modal_doc, quiz_me_text_doc

generation:
  activate: false
  prompt_strategy: flashcards

  flashcards:
    topic: community acquired pneumonia

  microbiology_scenario:
    param1:
    param2:

  anatomy_scenario:
    param1:
    param2:
